main:
  - identifier: home
    name: Home
    url: /home
    weight: 1
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 2
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 3
