mainSections: ['posts']
limit: 10

sidebar:
  avatar:
    enabled: true
    local: true
    src: profile-picture.png

widgets:
  homepage:
    - type: categories
    - type: tag-cloud
      params:
        limit: 100
